# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Society of Software Engineers at MSOE
email: flemingg@msoe.edu
description: >- # this means to ignore newlines until "baseurl:"
  MSOE''s Society of Software Engineers is a student run professional organization that strives to empower Software Engineers and all people who love to code for a better future in the industry. Through collaboration, workshops, technical discussions and networking events, SSE strengthens student''s technical, networking and soft skills. With constant community outreach, SSE ensures that relationships are being built to keep students current and strong in the fast moving tech world.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: msoe-sse
github_username:  msoe-sse-web
future-date: true
future: true
# Build settings
markdown: kramdown
theme: thunder
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
